services:
  nginx-react:
    build: .
    ports: 
      - "8080:8080"
    restart: always
    environment:
      HOST: localhost
      SERVER_NAME: localhost
      PORT: 8080
      API_SERVER_NAME: rest-api
    networks: 
      - backend


networks: 
  backend:
    external: true